app = 'streetlight-api'
primary_region = 'sjc'

[build]
  dockerfile = './Dockerfile'

[env]
  PORT = '4000'

[[services]]
  protocol = 'tcp'
  internal_port = 4000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
