app = "streetlight-api"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "4000"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 4000
  processes = ["app"]
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
