name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.15
        uses: actions/setup-node@v4
        with:
          node-version: "22.15"
      - name: Use pnpm 10.27
        run: npm install --global pnpm@10.27.0
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Prepare local database
        run: pnpm db:migrate && pnpm db:seed
      - name: Check
        run: pnpm check
